import { Dimensions, StyleSheet } from "react-native";
import { Theme } from "@/src/theme/colors";
import { fontSize, fonts } from "@/src/theme/fonts";
import {
  heightScale,
  moderateHeightScale,
  moderateWidthScale,
  widthScale,
} from "@/src/theme/dimensions";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.darkGreen,
    },
    sheet: {
      flex: 1,
      backgroundColor: theme.background,
      borderTopLeftRadius: moderateWidthScale(18),
      borderTopRightRadius: moderateWidthScale(18),
      overflow: "hidden",
    },
    scrollContent: {
      paddingHorizontal: moderateWidthScale(15),
      paddingTop: moderateHeightScale(12),
      paddingBottom: moderateHeightScale(14),
      gap: moderateHeightScale(12),
    },
    cardShadow: {
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    statusIdRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: moderateWidthScale(12),
    },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(6),
      borderRadius: moderateWidthScale(20),
      gap: moderateWidthScale(6),
    },
    statusDot: {
      width: moderateWidthScale(7),
      height: moderateWidthScale(7),
      borderRadius: moderateWidthScale(4),
    },
    statusOngoing: {
      backgroundColor: theme.orangeBrown015,
    },
    statusActive: {
      backgroundColor: theme.apptBlueBg,
    },
    statusComplete: {
      backgroundColor: theme.apptMintBg,
    },
    statusAwaitingOutcome: {
      backgroundColor: theme.orangeBrown015,
    },
    statusCancelled: {
      backgroundColor: theme.lightRed,
    },
    statusText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontBold,
    },
    statusTextOngoing: {
      color: theme.appointmentStatusText,
    },
    statusTextActive: {
      color: theme.apptBlueAccent,
    },
    statusTextComplete: {
      color: theme.apptMintAccent,
    },
    statusTextAwaitingOutcome: {
      color: theme.appointmentStatusText,
    },
    statusTextCancelled: {
      color: theme.red,
    },
    statusDotOngoing: {
      backgroundColor: theme.toggleActive,
    },
    statusDotActive: {
      backgroundColor: theme.apptBlueAccent,
    },
    statusDotComplete: {
      backgroundColor: theme.apptMintAccent,
    },
    statusDotAwaitingOutcome: {
      backgroundColor: theme.appointmentStatusText,
    },
    statusDotCancelled: {
      backgroundColor: theme.red,
    },
    bookingIdBlock: {
      alignItems: "flex-end",
      flexShrink: 1,
    },
    bookingIdText: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    bookedOnText: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      marginTop: moderateHeightScale(2),
    },
    serviceCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(18),
      padding: moderateWidthScale(14),
    },
    serviceCardRow: {
      flexDirection: "row",
      gap: moderateWidthScale(12),
    },
    serviceImage: {
      width: widthScale(114),
      height: widthScale(114),
      borderRadius: moderateWidthScale(14),
      backgroundColor: theme.lightGreen05,
    },
    serviceInfo: {
      flex: 1,
      justifyContent: "flex-start",
    },
    serviceTitle: {
      fontSize: fontSize.size18,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      textTransform: "uppercase",
      marginBottom: moderateHeightScale(2),
    },
    serviceSubtitle: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
      marginBottom: moderateHeightScale(8),
    },
    tagsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: moderateWidthScale(6),
    },
    tagPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(4),
      backgroundColor: theme.lightGreen07,
      paddingHorizontal: moderateWidthScale(8),
      paddingVertical: moderateHeightScale(4),
      borderRadius: moderateWidthScale(20),
    },
    tagText: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    serviceDescription: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      lineHeight: fontSize.size17,
      marginTop: moderateHeightScale(8),
    },
    infoWrap: {
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    infoGrid: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: moderateWidthScale(0),
    },
    infoColumn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.borderLight,
      borderTopLeftRadius: moderateWidthScale(12),
      borderTopRightRadius: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(8),
      paddingHorizontal: moderateWidthScale(8),
      gap: moderateWidthScale(5),
      minWidth: 0,
    },
    infoColumnPressable: {
      flex: 1,
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.borderLight,
      borderTopLeftRadius: moderateWidthScale(12),
      borderTopRightRadius: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(8),
      paddingHorizontal: moderateWidthScale(8),
      gap: moderateWidthScale(4),
      minWidth: 0,
    },
    infoIconCircle: {
      width: widthScale(26),
      height: widthScale(26),
      borderRadius: widthScale(13),
      backgroundColor: theme.buttonBack,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      marginTop: moderateHeightScale(1),
    },
    infoTextCol: {
      flex: 1,
      minWidth: 0,
      justifyContent: "flex-start",
    },
    infoLabel: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
      marginBottom: moderateHeightScale(2),
    },
    infoValue: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      lineHeight: fontSize.size13,
    },
    infoValueDuration: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontBold,
      color: theme.text,
      lineHeight: fontSize.size13,
    },
    infoValueSecondary: {
      fontSize: fontSize.size9,
      fontFamily: fonts.fontSemiBold,
      color: theme.darkGreen,
      marginTop: moderateHeightScale(1),
      lineHeight: fontSize.size12,
    },
    infoChevron: {
      flexShrink: 0,
      marginTop: moderateHeightScale(8),
      marginLeft: moderateWidthScale(1),
    },
    locationCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(12),
      paddingHorizontal: moderateWidthScale(12),
      minHeight: heightScale(102),
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(14),
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    locationTouchable: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(10),
      minWidth: 0,
      paddingRight: moderateWidthScale(6),
    },
    locationAvatar: {
      width: widthScale(64),
      height: widthScale(64),
      borderRadius: widthScale(32),
      backgroundColor: theme.lightGreen05,
    },
    locationInfo: {
      flex: 1,
      gap: moderateHeightScale(4),
      minWidth: 0,
      paddingRight: moderateWidthScale(4),
    },
    locationName: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      textTransform: "capitalize",
    },
    locationAddressRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: moderateWidthScale(4),
      paddingRight: moderateWidthScale(4),
    },
    locationAddressPin: {
      marginTop: moderateHeightScale(1),
    },
    locationAddress: {
      flex: 1,
      fontSize: fontSize.size11,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      lineHeight: fontSize.size15,
    },
    locationAffiliation: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
    },
    locationAffiliationName: {
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    getDirectionsButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: moderateWidthScale(4),
      backgroundColor: theme.lightGreen05,
      paddingHorizontal: moderateWidthScale(10),
      paddingVertical: moderateHeightScale(7),
      borderRadius: moderateWidthScale(999),
      flexShrink: 0,
      marginLeft: moderateWidthScale(2),
    },
    getDirectionsText: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    actionCardsRow: {
      flexDirection: "row",
      gap: moderateWidthScale(10),
    },
    actionCard: {
      flex: 1,
      borderRadius: moderateWidthScale(20),
      paddingHorizontal: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(12),
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(6),
      minHeight: heightScale(68),
    },
    actionCardPrimary: {
      backgroundColor: theme.buttonBack,
    },
    actionCardSecondary: {
      backgroundColor: theme.lightGreen07,
    },
    actionCardTextWrap: {
      flex: 1,
      minWidth: 0,
      gap: moderateHeightScale(5),
    },
    actionCardTitle: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontBold,
    },
    actionCardTitlePrimary: {
      color: theme.white,
    },
    actionCardTitleSecondary: {
      color: theme.darkGreen,
    },
    actionCardSubtitle: {
      fontSize: fontSize.size8,
      fontFamily: fonts.fontRegular,
    },
    actionCardSubtitlePrimary: {
      color: theme.white80,
    },
    actionCardSubtitleSecondary: {
      color: theme.lightGreen,
    },
    actionCardChevron: {
      flexShrink: 0,
    },
    paymentCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(18),
      paddingVertical: moderateHeightScale(12),
      paddingHorizontal: moderateWidthScale(14),
      flexDirection: "row",
      alignItems: "center",
      minHeight: heightScale(88),
    },
    paymentLeft: {
      flex: 1.15,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: moderateWidthScale(10),
      paddingRight: moderateWidthScale(12),
    },
    paymentIconCircle: {
      width: widthScale(38),
      height: widthScale(38),
      borderRadius: widthScale(19),
      backgroundColor: theme.lightGreen07,
      alignItems: "center",
      justifyContent: "center",
    },
    paymentTextCol: {
      flex: 1,
      gap: moderateHeightScale(2),
      minWidth: 0,
    },
    paymentLabel: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
    },
    paymentTitle: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    paymentSubtitle: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
    },
    paymentDivider: {
      width: 1,
      alignSelf: "stretch",
      backgroundColor: theme.borderLight,
    },
    paymentRight: {
      flex: 1,
      justifyContent: "center",
      paddingLeft: moderateWidthScale(14),
      gap: moderateHeightScale(4),
    },
    paymentAmount: {
      fontSize: fontSize.size20,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    paymentBreakdownCard: {
      marginTop: moderateHeightScale(6),
      borderRadius: moderateWidthScale(10),
      backgroundColor: theme.lightGreen05,
      borderWidth: 1,
      borderColor: theme.borderLight,
      paddingHorizontal: moderateWidthScale(10),
      paddingVertical: moderateHeightScale(8),
      gap: moderateHeightScale(4),
    },
    paymentBreakdownRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    paymentBreakdownLabel: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      flex: 1,
      marginRight: moderateWidthScale(8),
      textTransform: "capitalize",
    },
    paymentBreakdownValue: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    paymentBreakdownTotalLabel: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    paymentBreakdownTotalValue: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    paymentBreakdownDivider: {
      height: 1,
      backgroundColor: theme.borderLight,
      marginVertical: moderateHeightScale(2),
    },
    payOnlineButton: {
      height: moderateHeightScale(34),
      paddingHorizontal: moderateWidthScale(12),
      borderRadius: moderateWidthScale(8),
      marginTop: moderateHeightScale(8),
    },
    payOnlineButtonText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
    },
    notesCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(18),
      padding: moderateWidthScale(14),
      flexDirection: "row",
      gap: moderateWidthScale(10),
      alignItems: "flex-start",
      minHeight: heightScale(86),
    },
    notesTextCol: {
      flex: 1,
      gap: moderateHeightScale(4),
    },
    notesLabel: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
    },
    notesText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      lineHeight: fontSize.size20,
    },
    inspirationCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(18),
      padding: moderateWidthScale(14),
      gap: moderateHeightScale(10),
    },
    inspirationHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(10),
    },
    inspirationTitle: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    inspirationRow: {
      flexDirection: "row",
      gap: moderateWidthScale(10),
      alignItems: "center",
    },
    inspirationThumb: {
      width: widthScale(64),
      height: widthScale(64),
      borderRadius: moderateWidthScale(10),
      backgroundColor: theme.grey15,
    },
    inspirationThumbWrap: {
      width: widthScale(64),
      height: widthScale(64),
      borderRadius: moderateWidthScale(10),
      overflow: "hidden",
      position: "relative",
    },
    inspirationPlayBadge: {
      position: "absolute",
      right: moderateWidthScale(4),
      bottom: moderateHeightScale(4),
      width: moderateWidthScale(22),
      height: moderateWidthScale(22),
      borderRadius: moderateWidthScale(11),
      backgroundColor: theme.lightGreen5,
      alignItems: "center",
      justifyContent: "center",
    },
    inspirationMeta: {
      flex: 1,
      gap: moderateHeightScale(4),
    },
    inspirationLookTag: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    inspirationCaption: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
    },
    assignedStaffRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(12),
      paddingHorizontal: moderateWidthScale(12),
      gap: moderateWidthScale(10),
    },
    assignedStaffAvatar: {
      width: widthScale(36),
      height: widthScale(36),
      borderRadius: widthScale(18),
      backgroundColor: theme.lightGreen05,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    assignedStaffAvatarImage: {
      width: "100%",
      height: "100%",
    },
    assignedStaffTextContainer: {
      flex: 1,
    },
    assignedStaffLabel: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
      marginBottom: moderateHeightScale(2),
    },
    assignedStaffName: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      textTransform: "capitalize",
    },
    imagesSection: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(18),
      padding: moderateWidthScale(14),
    },
    imagesSectionTitle: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      marginBottom: moderateHeightScale(12),
    },
    imagesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: moderateWidthScale(8),
    },
    imageCard: {
      width:
        (Dimensions.get("window").width -
          moderateWidthScale(16) * 2 -
          moderateWidthScale(14) * 2 -
          moderateWidthScale(8) * 2) /
        3,
      height:
        (Dimensions.get("window").width -
          moderateWidthScale(16) * 2 -
          moderateWidthScale(14) * 2 -
          moderateWidthScale(8) * 2) /
        3,
      borderRadius: moderateWidthScale(10),
      overflow: "hidden",
      backgroundColor: theme.lightGreen2,
      borderWidth: 1,
      borderColor: theme.borderLight,
      position: "relative",
    },
    imageCardImage: {
      width: "100%",
      height: "100%",
    },
    imageShareIcon: {
      position: "absolute",
      top: moderateHeightScale(6),
      left: moderateWidthScale(6),
      width: moderateWidthScale(32),
      height: moderateWidthScale(32),
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.lightGreen6,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 2,
    },
    imageDownloadIcon: {
      position: "absolute",
      bottom: moderateHeightScale(6),
      right: moderateWidthScale(6),
      width: moderateWidthScale(32),
      height: moderateWidthScale(32),
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.lightGreen6,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 2,
    },
    tipReceiptSection: {
      marginTop: moderateHeightScale(4),
    },
    tipReceiptCard: {
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.lightGreen07,
      borderWidth: 1,
      borderColor: theme.lightGreen1,
      padding: moderateWidthScale(16),
      overflow: "hidden",
    },
    tipReceiptTopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(12),
    },
    tipReceiptAvatarWrap: {
      position: "relative",
    },
    tipReceiptAvatar: {
      width: widthScale(52),
      height: widthScale(52),
      borderRadius: widthScale(26),
      backgroundColor: theme.emptyProfileImage,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderWidth: 2,
      borderColor: theme.orangeBrown,
    },
    tipReceiptAvatarImage: {
      width: "100%",
      height: "100%",
    },
    tipReceiptInitial: {
      fontSize: fontSize.size18,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    tipReceiptBadge: {
      position: "absolute",
      right: -moderateWidthScale(2),
      bottom: -moderateHeightScale(2),
      width: widthScale(20),
      height: widthScale(20),
      borderRadius: widthScale(10),
      backgroundColor: theme.buttonBack,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: theme.white,
    },
    tipReceiptInfo: {
      flex: 1,
    },
    tipReceiptEyebrow: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.orangeBrown,
      letterSpacing: 0.4,
      marginBottom: moderateHeightScale(4),
    },
    tipReceiptTitle: {
      fontSize: fontSize.size16,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      textTransform: "capitalize",
      marginBottom: moderateHeightScale(2),
    },
    tipReceiptSubtitle: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      lineHeight: fontSize.size18,
    },
    tipReceiptAmountPill: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(20),
      paddingHorizontal: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(8),
      borderWidth: 1,
      borderColor: theme.lightGreen1,
      alignItems: "center",
      justifyContent: "center",
      minWidth: widthScale(64),
    },
    tipReceiptAmount: {
      fontSize: fontSize.size16,
      fontFamily: fonts.fontBold,
      color: theme.buttonBack,
    },
    tipReceiptFooter: {
      marginTop: moderateHeightScale(12),
      paddingTop: moderateHeightScale(12),
      borderTopWidth: 1,
      borderTopColor: theme.lightGreen1,
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(8),
    },
    tipReceiptFooterText: {
      flex: 1,
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      lineHeight: fontSize.size16,
    },
    cancellationPolicyCard: {
      backgroundColor: theme.orangeBrown01,
      borderRadius: moderateWidthScale(14),
      borderWidth: 1,
      borderColor: theme.orangeBrown30,
      paddingHorizontal: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(14),
      marginBottom: moderateHeightScale(12),
      overflow: "hidden",
    },
    cancellationPolicyAccent: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: moderateWidthScale(4),
      backgroundColor: theme.selectCard,
    },
    cancellationPolicyHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(10),
      marginBottom: moderateHeightScale(12),
      paddingLeft: moderateWidthScale(4),
    },
    cancellationPolicyIconWrap: {
      width: widthScale(36),
      height: widthScale(36),
      borderRadius: moderateWidthScale(36 / 2),
      backgroundColor: theme.selectCard,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    cancellationPolicyTitle: {
      flex: 1,
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    cancellationPolicyRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingVertical: moderateHeightScale(8),
      borderTopWidth: 1,
      borderTopColor: theme.orangeBrown30,
      gap: moderateWidthScale(10),
      paddingLeft: moderateWidthScale(4),
    },
    cancellationPolicyRowLabel: {
      flex: 1,
      fontSize: fontSize.size13,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
      lineHeight: fontSize.size17,
    },
    cancellationPolicyRowValue: {
      flex: 1.2,
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen5,
      textAlign: "right",
      lineHeight: fontSize.size17,
    },
    cancellationPolicyBodyText: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      lineHeight: fontSize.size18,
      marginTop: moderateHeightScale(12),
    },
    visitStatusCard: {
      marginTop: moderateHeightScale(16),
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(12),
      borderWidth: 1,
      borderColor: theme.lightGreen2,
      paddingHorizontal: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(12),
    },
    visitStatusLabel: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    visitStatusReason: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen5,
      marginTop: moderateHeightScale(6),
      lineHeight: fontSize.size18,
    },
    bottomActions: {
      paddingHorizontal: moderateWidthScale(16),
      paddingBottom: moderateHeightScale(14),
      paddingTop: moderateHeightScale(10),
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
      gap: moderateHeightScale(10),
    },
    completeButton: {
      height: heightScale(54),
      borderRadius: moderateWidthScale(14),
    },
    outcomeActionsRow: {
      flexDirection: "row",
      gap: moderateWidthScale(8),
    },
    outcomeActionButton: {
      flex: 1,
      height: heightScale(52),
      borderRadius: moderateWidthScale(14),
      alignItems: "center",
      justifyContent: "center",
    },
    outcomeCompletedButton: {
      backgroundColor: theme.apptMintBg,
      borderWidth: 1,
      borderColor: theme.apptMintAccent,
    },
    outcomeNoShowButton: {
      backgroundColor: theme.lightRed,
      borderWidth: 1,
      borderColor: theme.lightRedBorder,
    },
    outcomeCompletedButtonText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.apptMintAccent,
    },
    outcomeNoShowButtonText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.red,
    },
    bottomButtonsRow: {
      flexDirection: "row",
      gap: moderateWidthScale(10),
    },
    bottomOutlineButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: moderateWidthScale(8),
      backgroundColor: theme.white,
      borderWidth: 1.5,
      borderColor: theme.darkGreen,
      borderRadius: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(14),
      minHeight: heightScale(52),
    },
    bottomOutlineButtonText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    bottomCancelButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: moderateWidthScale(8),
      backgroundColor: theme.white,
      borderWidth: 1.5,
      borderColor: theme.red,
      borderRadius: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(14),
      minHeight: heightScale(52),
    },
    bottomCancelButtonText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.red,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.background,
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: moderateWidthScale(20),
      backgroundColor: theme.background,
    },
    errorText: {
      fontSize: fontSize.size16,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      textAlign: "center",
      marginBottom: moderateHeightScale(16),
    },
  });
