import { Theme } from "@/src/theme/colors";
import { StyleSheet, Dimensions } from "react-native";
import {
  moderateHeightScale,
  moderateWidthScale,
  widthScale,
} from "@/src/theme/dimensions";
import { fontSize, fonts } from "@/src/theme/fonts";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    contentContainer: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: moderateHeightScale(20),
      paddingHorizontal: moderateWidthScale(20),
    },
    fieldContainer: {
      marginTop: moderateHeightScale(24),
    },
    label: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontMedium,
      color: theme.text,
      marginBottom: moderateHeightScale(8),
    },
    labelInRow: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontMedium,
      color: theme.text,
      flexShrink: 1,
    },
    required: {
      color: theme.red,
    },
    fileInput: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.borderLine,
      borderRadius: moderateWidthScale(8),
      paddingHorizontal: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(14),
      minHeight: moderateHeightScale(48),
    },
    fileInputText: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontRegular,
      color: theme.text,
      flex: 1,
    },
    imagePreviewContainer: {
      marginTop: moderateHeightScale(16),
      position: "relative",
      width: "100%",
      aspectRatio: 1,
      // height: moderateHeightScale(200),
      borderRadius: moderateWidthScale(8),
      overflow: "hidden",
      backgroundColor: theme.grey15,
    },
    imagePreview: {
      width: "100%",
      height: "100%",
    },
    deleteButton: {
      position: "absolute",
      top: moderateHeightScale(8),
      right: moderateWidthScale(8),
      width: moderateWidthScale(32),
      height: moderateWidthScale(32),
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.red,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1,
    },
    mediaGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: moderateWidthScale(10),
      marginTop: moderateHeightScale(14),
    },
    mediaItem: {
      position: "relative",
      width:
        (SCREEN_WIDTH - moderateWidthScale(40) - moderateWidthScale(24)) / 3,
      aspectRatio: 1,
      borderRadius: moderateWidthScale(8),
      overflow: "hidden",
      backgroundColor: theme.grey15,
    },
    mediaThumbnail: {
      width: "100%",
      height: "100%",
    },
    videoThumbnailContainer: {
      width: "100%",
      height: "100%",
      position: "relative",
    },
    videoThumbnail: {
      width: "100%",
      height: "100%",
      backgroundColor: theme.grey15,
      alignItems: "center",
      justifyContent: "center",
    },
    videoPlayIcon: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    deleteButtonSmall: {
      position: "absolute",
      top: moderateHeightScale(4),
      right: moderateWidthScale(4),
      width: moderateWidthScale(24),
      height: moderateWidthScale(24),
      borderRadius: moderateWidthScale(12),
      backgroundColor: theme.red,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1,
    },
    hintText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen4,
      marginTop: moderateHeightScale(8),
    },
    /** Generate Reel — media picker trigger */
    mediaPickerCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(14),
      backgroundColor: theme.white,
      borderWidth: 1.5,
      borderColor: theme.borderNormal,
      borderStyle: "dashed",
      borderRadius: moderateWidthScale(14),
      paddingHorizontal: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(16),
    },
    mediaPickerCardFilled: {
      borderStyle: "solid",
      borderColor: theme.borderLight,
      backgroundColor: theme.lightGreen05,
    },
    mediaPickerIconCircle: {
      width: widthScale(44),
      height: widthScale(44),
      borderRadius: moderateWidthScale(22),
      backgroundColor: theme.buttonBack,
      alignItems: "center",
      justifyContent: "center",
    },
    mediaPickerTextCol: {
      flex: 1,
      gap: moderateHeightScale(2),
    },
    mediaPickerTitle: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    mediaPickerSubtitle: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
    },
    /** Generate Reel — music card */
    musicCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(12),
      backgroundColor: theme.white,
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: moderateWidthScale(14),
      paddingHorizontal: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(14),
    },
    musicCardEmpty: {
      borderStyle: "dashed",
      borderWidth: 1.5,
      borderColor: theme.borderNormal,
      backgroundColor: theme.lightGreen05,
    },
    musicIconCircle: {
      width: widthScale(42),
      height: widthScale(42),
      borderRadius: moderateWidthScale(21),
      backgroundColor: theme.buttonBack,
      alignItems: "center",
      justifyContent: "center",
    },
    musicTextCol: {
      flex: 1,
      gap: moderateHeightScale(2),
      minWidth: 0,
    },
    musicTitle: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontMedium,
      color: theme.text,
    },
    musicSubtitle: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
    },
    musicActionBtn: {
      paddingHorizontal: moderateWidthScale(10),
      paddingVertical: moderateHeightScale(6),
      borderRadius: moderateWidthScale(8),
      backgroundColor: theme.lightGreen015,
    },
    musicActionText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    musicRemoveBtn: {
      width: moderateWidthScale(32),
      height: moderateWidthScale(32),
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.lightRed,
      alignItems: "center",
      justifyContent: "center",
    },
    optionalBadge: {
      alignSelf: "flex-start",
      marginLeft: moderateWidthScale(8),
      paddingHorizontal: moderateWidthScale(8),
      paddingVertical: moderateHeightScale(2),
      borderRadius: moderateWidthScale(6),
      backgroundColor: theme.lightGreen015,
    },
    optionalBadgeText: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
    },
    labelRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: moderateHeightScale(8),
    },
    /** Bottom sheet option cards for reel media */
    sheetOptionCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(14),
      paddingVertical: moderateHeightScale(14),
      paddingHorizontal: moderateWidthScale(4),
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    sheetOptionIcon: {
      width: widthScale(44),
      height: widthScale(44),
      borderRadius: moderateWidthScale(22),
      backgroundColor: theme.lightGreen07,
      alignItems: "center",
      justifyContent: "center",
    },
    sheetOptionTextCol: {
      flex: 1,
      gap: moderateHeightScale(2),
    },
    sheetOptionTitle: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    sheetOptionDesc: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
    },
    audioFileContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: moderateHeightScale(16),
      backgroundColor: theme.grey15,
      borderRadius: moderateWidthScale(8),
      paddingHorizontal: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(12),
      gap: moderateWidthScale(12),
    },
    audioFileName: {
      flex: 1,
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.text,
    },
    buttonContainer: {
      marginTop: moderateHeightScale(4),
      marginBottom: moderateHeightScale(24),
      paddingHorizontal: moderateWidthScale(20),
    },
    optionItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: moderateHeightScale(16),
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    optionIcon: {
      marginRight: moderateWidthScale(16),
    },
    optionText: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      flex: 1,
    },
    textArea: {
      borderWidth: 1,
      borderRadius: moderateWidthScale(8),
      paddingHorizontal: moderateWidthScale(16),
      paddingVertical: moderateHeightScale(12),
      minHeight: moderateHeightScale(120),
      fontSize: fontSize.size15,
      fontFamily: fonts.fontRegular,
      textAlignVertical: "top",
    },
    hairTryonOptionsContainer: {
      flexDirection: "column",
      gap: moderateHeightScale(20),
      marginVertical: moderateHeightScale(24),
    },
    hairTryonOptionCard: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(16),
      borderWidth: 1,
      borderColor: theme.borderLight,
      padding: moderateWidthScale(20),
      paddingVertical: moderateHeightScale(20),
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: moderateWidthScale(8),
      elevation: 3,
      overflow: "hidden",
    },
    hairTryonOptionCardSelected: {
      borderColor: theme.darkGreen,
      borderWidth: 2,
      backgroundColor: theme.lightGreen05,
      shadowOpacity: 0.1,
      shadowRadius: moderateWidthScale(10),
      elevation: 4,
    },
    hairTryonOptionCardDisabled: {
      borderColor: theme.borderLight,
      opacity: 0.65,
    },
    hairTryonOptionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: moderateHeightScale(12),
      paddingBottom: moderateHeightScale(10),
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    hairTryonOptionTitle: {
      fontSize: fontSize.size17,
      fontFamily: fonts.fontBold,
      color: theme.text,
      flex: 1,
      paddingRight: moderateWidthScale(8),
    },
    hairTryonOptionBadge: {
      backgroundColor: theme.darkGreen,
      paddingHorizontal: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(6),
      borderRadius: moderateWidthScale(20),
    },
    hairTryonOptionBadgeText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.white,
    },
    hairTryonOptionSubtitle: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen4,
      marginBottom: moderateHeightScale(8),
    },
    hairTryonOptionDesc: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen,
      marginBottom: moderateHeightScale(14),
      lineHeight: 22,
    },
    hairTryonOptionButton: {
      alignSelf: "stretch",
      paddingVertical: moderateHeightScale(12),
      paddingHorizontal: moderateWidthScale(20),
      borderRadius: moderateWidthScale(10),
      marginTop: moderateHeightScale(8),
      alignItems: "center",
      justifyContent: "center",
    },
    hairTryonOptionButtonActive: {
      backgroundColor: theme.darkGreen,
    },
    hairTryonOptionButtonInactive: {
      backgroundColor: theme.grey15,
    },
    hairTryonOptionButtonText: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontMedium,
    },
    hairTryonOptionButtonTextActive: {
      color: theme.white,
    },
    hairTryonOptionButtonTextInactive: {
      color: theme.lightGreen,
    },
    hairTryonChangeSelectionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: moderateHeightScale(16),
    },
    hairTryonSelectedTypeLabel: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontMedium,
      color: theme.text,
    },
    hairTryonChangeSelectionText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen,
      textDecorationLine: "underline",
      textDecorationColor: theme.lightGreen,
    },
    creditBanner: {
      width: "100%",
      paddingHorizontal: moderateWidthScale(20),
      paddingVertical: moderateHeightScale(6),
      backgroundColor: theme.darkGreen,
      // borderBottomWidth: 1,
      // borderBottomColor: theme.borderLine,
    },
    creditBannerText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.white80,
      textAlign: "center",
    },
  });
