export const IMAGES = {
  welcomeLogo: require("@/assets/lotties/logo.json"),
  socialBackgroud: require("@/assets/images/socialBackgroud.png"),
  mapPins: require("@/assets/images/mapPin.png"),
  acceptTermBackS: require("@/assets/images/acceptTermBackS.png"),
  acceptTermBackB: require("@/assets/images/acceptTermBackB.png"),
  introductionBack1B: require("@/assets/images/introductionBack1B.png"),
  introductionBack1C: require("@/assets/images/introductionBack1C.png"),
  introductionBack2B: require("@/assets/images/introductionBack2B.png"),
  introductionBack2C: require("@/assets/images/introductionBack2C.png"),
  aiFeatureBackB: require("@/assets/images/aiFeatureBackB.png"),
  aiFeatureBackC: require("@/assets/images/aiFeatureBackC.png"),
  plusLoader: require("@/assets/lotties/plusLoader.json"),
  location: require("@/assets/images/location.png"),
  logo3d: require("@/assets/images/logo3d.png"),
  tryOnBack: require("@/assets/images/tryOnBack.png"),
  femaleAgent: require("@/assets/images/female-agent.png"),
};
