import { Theme } from "@/src/theme/colors";
import { StyleSheet } from "react-native";
import {
  moderateHeightScale,
  moderateWidthScale,
  heightScale,
  widthScale,
} from "@/src/theme/dimensions";
import { fontSize, fonts } from "@/src/theme/fonts";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingVertical: moderateHeightScale(24),
      paddingHorizontal: moderateWidthScale(20),
      justifyContent: "flex-start",
    },
    headerContainer: {
      alignItems: "center",
    },
    headerButton: {
      width: "100%",
      borderRadius: moderateWidthScale(12),
      overflow: "hidden",
    },
    headerGradient: {
      paddingVertical: moderateHeightScale(16),
      paddingHorizontal: moderateWidthScale(24),
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: fontSize.size20,
      fontFamily: fonts.fontBold,
      color: theme.white,
      textAlign: "center",
    },
    featuresContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    featureShadow: {
      width: "48%",
      marginTop: moderateHeightScale(16),
      borderRadius: moderateWidthScale(18),
      backgroundColor: theme.background,
      shadowColor: theme.darkGreen,
      shadowOffset: {
        width: 0,
        height: moderateHeightScale(8),
      },
      shadowOpacity: 0.28,
      shadowRadius: moderateWidthScale(12),
      elevation: 10,
    },
    featureShadowLarge: {
      width: "48%",
      marginTop: moderateHeightScale(16),
      borderRadius: moderateWidthScale(18),
      backgroundColor: theme.background,
      shadowColor: theme.darkGreen,
      shadowOffset: {
        width: 0,
        height: moderateHeightScale(8),
      },
      shadowOpacity: 0.28,
      shadowRadius: moderateWidthScale(12),
      elevation: 10,
    },
    featureBox: {
      height: heightScale(148),
      borderRadius: moderateWidthScale(18),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.lightGreen4,
    },
    featureBoxLarge: {
      height: heightScale(220),
      borderRadius: moderateWidthScale(18),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.lightGreen4,
    },
    gradientContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: moderateHeightScale(20),
      paddingHorizontal: moderateWidthScale(12),
      gap: moderateHeightScale(14),
    },
    cardHighlight: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: "42%",
    },
    iconContainer: {
      width: moderateWidthScale(64),
      height: moderateWidthScale(64),
      borderRadius: moderateWidthScale(32),
      backgroundColor: theme.white15,
      borderWidth: 1,
      borderColor: theme.white50,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: moderateHeightScale(3),
      },
      shadowOpacity: 0.22,
      shadowRadius: moderateWidthScale(6),
      elevation: 4,
    },
    featureTitle: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.white,
      textAlign: "center",
      letterSpacing: 0.2,
    },
    actionButtonsRow: {
      flexDirection: "row",
      gap: moderateWidthScale(12),
      marginBottom: moderateHeightScale(8),
    },
    actionButtonFlex: {
      flex: 1,
    },
    actionButtonShadow: {
      flex: 1,
      borderRadius: moderateWidthScale(14),
      backgroundColor: theme.background,
      shadowColor: theme.darkGreen,
      shadowOffset: {
        width: 0,
        height: moderateHeightScale(5),
      },
      shadowOpacity: 0.22,
      shadowRadius: moderateWidthScale(8),
      elevation: 7,
    },
    actionButtonCard: {
      borderRadius: moderateWidthScale(14),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.lightGreen4,
      minHeight: moderateHeightScale(78),
    },
    actionButtonGradient: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: moderateHeightScale(14),
      paddingHorizontal: moderateWidthScale(8),
      minHeight: moderateHeightScale(78),
    },
    actionButtonIconWrap: {
      width: moderateWidthScale(40),
      height: moderateWidthScale(40),
      borderRadius: moderateWidthScale(20),
      backgroundColor: theme.white15,
      borderWidth: 1,
      borderColor: theme.white50,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: moderateHeightScale(8),
    },
    actionButtonLabel: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.white,
      textAlign: "center",
      letterSpacing: 0.15,
    },
    footerContainer: {
      paddingVertical: moderateHeightScale(44),
      paddingHorizontal: moderateWidthScale(20),
    },
    // Inline tutorial video (inside box)
    tutorialVideoRoot: {
      flex: 1,
      width: "100%",
      backgroundColor: theme.black,
      borderRadius: moderateWidthScale(16),
    },
    tutorialVideo: {
      width: "100%",
      flex: 1,
      minHeight: heightScale(120),
    },
    tutorialPlayOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "transparent",
    },
    tutorialPlayCircle: {
      width: widthScale(44),
      height: widthScale(44),
      borderRadius: widthScale(22),
      backgroundColor: theme.orangeBrown,
      justifyContent: "center",
      alignItems: "center",
    },
    tutorialControlsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: moderateHeightScale(2),
      paddingHorizontal: moderateWidthScale(2),
      gap: moderateWidthScale(12),
    },
    tutorialControlsRowWrapper: {
      position: "absolute",
      bottom: moderateHeightScale(10),
      left: 0,
      right: 0,
    },
    tutorialControlBtn: {
      paddingVertical: moderateHeightScale(2),
      paddingHorizontal: moderateWidthScale(6),
      borderRadius: moderateWidthScale(5),
      backgroundColor: theme.lightGreen,
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.8,
    },
    tutorialControlBtnText: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontMedium,
      color: theme.white,
    },
    tutorialExpandBtn: {
      position: "absolute",
      top: moderateHeightScale(6),
      right: moderateWidthScale(6),
      width: widthScale(28),
      height: widthScale(28),
      borderRadius: widthScale(14),
      backgroundColor: theme.lightGreen,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 10,
      opacity: 0.8,
    },
    tutorialTimeText: {
      fontSize: fontSize.size10,
      fontFamily: fonts.fontRegular,
      color: theme.white70,
      textAlign: "center",
      marginTop: moderateHeightScale(2),
    },
    tutorialTimeTextAbsolute: {
      position: "absolute",
      bottom: moderateHeightScale(48),
      left: 0,
      right: 0,
      fontSize: fontSize.size10,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      textAlign: "center",
    },
  });
