import { Theme } from "@/src/theme/colors";
import { fontSize, fonts } from "@/src/theme/fonts";
import {
  moderateHeightScale,
  moderateWidthScale,
} from "@/src/theme/dimensions";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingHorizontal: moderateWidthScale(16),
      paddingTop: moderateHeightScale(12),
      paddingBottom: moderateHeightScale(40),
    },
    monthBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: moderateHeightScale(14),
      gap: moderateWidthScale(8),
    },
    monthStepper: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(10),
      paddingHorizontal: moderateWidthScale(8),
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    monthArrow: {
      width: moderateWidthScale(36),
      height: moderateWidthScale(36),
      alignItems: "center",
      justifyContent: "center",
      borderRadius: moderateWidthScale(18),
    },
    monthArrowDisabled: {
      opacity: 0.3,
    },
    monthLabel: {
      flex: 1,
      textAlign: "center",
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    filterBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateWidthScale(4),
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(12),
      paddingHorizontal: moderateWidthScale(12),
      paddingVertical: moderateHeightScale(12),
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    filterBtnActive: {
      borderColor: theme.darkGreen,
      backgroundColor: theme.lightGreen05,
    },
    filterBtnText: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontMedium,
      color: theme.darkGreen,
    },
    contentFaded: {
      opacity: 0.45,
    },
    heroCard: {
      backgroundColor: theme.darkGreen,
      borderRadius: moderateWidthScale(16),
      padding: moderateWidthScale(20),
      marginBottom: moderateHeightScale(12),
    },
    heroEyebrow: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontMedium,
      color: theme.white70,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginBottom: moderateHeightScale(6),
    },
    heroAmount: {
      fontSize: fontSize.size32,
      fontFamily: fonts.fontBold,
      color: theme.white,
      marginBottom: moderateHeightScale(6),
    },
    heroDelta: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontMedium,
      color: theme.orangeBrown,
      marginBottom: moderateHeightScale(10),
    },
    heroDeltaFlat: {
      color: theme.white70,
    },
    payoutNote: {
      fontSize: fontSize.size11,
      fontFamily: fonts.fontRegular,
      color: theme.white70,
      lineHeight: moderateHeightScale(16),
    },
    card: {
      backgroundColor: theme.white,
      borderRadius: moderateWidthScale(14),
      padding: moderateWidthScale(16),
      marginBottom: moderateHeightScale(12),
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    sectionTitle: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontBold,
      color: theme.lightGreen6,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: moderateHeightScale(12),
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: moderateHeightScale(10),
    },
    rowLabel: {
      flex: 1,
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      paddingRight: moderateWidthScale(8),
    },
    rowValue: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    rowValueMuted: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen5,
      marginTop: moderateHeightScale(2),
    },
    deductionValue: {
      color: theme.red,
    },
    creditValue: {
      color: theme.buttonBack,
    },
    divider: {
      height: 1,
      backgroundColor: theme.borderLight,
      marginVertical: moderateHeightScale(8),
    },
    netRowLabel: {
      fontSize: fontSize.size15,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    netRowValue: {
      fontSize: fontSize.size16,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
    },
    sourceRow: {
      marginBottom: moderateHeightScale(12),
    },
    sourceTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    mutedCard: {
      backgroundColor: theme.lightGreen05,
      borderRadius: moderateWidthScale(14),
      padding: moderateWidthScale(16),
      marginBottom: moderateHeightScale(12),
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    mutedTitle: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontBold,
      color: theme.lightGreen6,
      marginBottom: moderateHeightScale(4),
    },
    mutedAmount: {
      fontSize: fontSize.size18,
      fontFamily: fonts.fontBold,
      color: theme.lightGreen6,
      marginBottom: moderateHeightScale(6),
    },
    mutedNote: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen5,
      lineHeight: moderateHeightScale(17),
    },
    feeNote: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontRegular,
      color: theme.selectCard,
      lineHeight: moderateHeightScale(17),
      marginTop: moderateHeightScale(4),
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: moderateHeightScale(10),
    },
    sectionTitleInline: {
      fontSize: fontSize.size12,
      fontFamily: fonts.fontBold,
      color: theme.lightGreen6,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    periodSubtitle: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontMedium,
      color: theme.lightGreen6,
      paddingHorizontal: moderateWidthScale(16),
      paddingTop: moderateHeightScale(8),
      paddingBottom: moderateHeightScale(4),
    },
    seeAll: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontMedium,
      color: theme.buttonBack,
    },
    emptyWrap: {
      alignItems: "center",
      paddingVertical: moderateHeightScale(48),
      paddingHorizontal: moderateWidthScale(24),
    },
    emptyTitle: {
      fontSize: fontSize.size16,
      fontFamily: fonts.fontBold,
      color: theme.darkGreen,
      textAlign: "center",
      marginBottom: moderateHeightScale(8),
    },
    emptySubtitle: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen6,
      textAlign: "center",
    },
    errorWrap: {
      alignItems: "center",
      paddingVertical: moderateHeightScale(40),
      paddingHorizontal: moderateWidthScale(20),
    },
    errorText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.darkGreen,
      textAlign: "center",
      marginBottom: moderateHeightScale(16),
    },
    txnErrorWrap: {
      paddingVertical: moderateHeightScale(16),
      alignItems: "center",
    },
    txnErrorText: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen6,
      textAlign: "center",
      marginBottom: moderateHeightScale(10),
    },
    retryLink: {
      fontSize: fontSize.size13,
      fontFamily: fonts.fontBold,
      color: theme.buttonBack,
    },
    skeletonHero: {
      height: moderateHeightScale(140),
      borderRadius: moderateWidthScale(16),
      backgroundColor: theme.lightGreen1,
      marginBottom: moderateHeightScale(12),
    },
    skeletonCard: {
      height: moderateHeightScale(120),
      borderRadius: moderateWidthScale(14),
      backgroundColor: theme.lightGreen1,
      marginBottom: moderateHeightScale(12),
    },
    loadingFooter: {
      paddingVertical: moderateHeightScale(16),
      alignItems: "center",
    },
    listContent: {
      paddingHorizontal: moderateWidthScale(16),
      paddingTop: moderateHeightScale(12),
      paddingBottom: moderateHeightScale(40),
    },
    emptyStateContainer: {
      paddingVertical: moderateHeightScale(48),
      alignItems: "center",
    },
    emptyStateText: {
      fontSize: fontSize.size14,
      fontFamily: fonts.fontRegular,
      color: theme.lightGreen6,
      textAlign: "center",
    },
  });
